---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cybersec
  name: app1
  # annotations:
  #   kubernetes.io/ingress.class: "traefik"
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  # tls:
  #   - hosts:
  #       - app1.minikube.local
  #     secretName: app1-ndl-nponsard.net-tls
  rules:
    - host: minikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-1
                port:
                  number: 3000

---
apiVersion: v1
kind: Service
metadata:
  namespace: cybersec
  name: app-1
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: app1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cybersec
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
        name: app1
    spec:
      containers:
        - name: app1
          image: sautax/cybersec-app-1:1.7
          ports:
            - containerPort: 3000
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
