---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cybersec
  name: app1
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - app1.ndl.nponsard.net
      secretName: app1-ndl-nponsard.net-tls
  rules:
    - host: app1.ndl.nponsard.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app1
                port:
                  number: 3000

---
apiVersion: v1
kind: Service
metadata:
  namespace: cybersec
  name: app1
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: app1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cybersec
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 3
  template:
    metadata:
      labels:
        app: app1
        name: app1
    spec:
      containers:
        - name: app1
          image: sautax/cybersec-app-1:latest
          ports:
            - containerPort: 3000
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
