---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cybersec
  name: app2
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - app2.ndl.nponsard.net
      secretName: app2-ndl-nponsard.net-tls
  rules:
    - host: app2.ndl.nponsard.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app2
                port:
                  number: 3000

---
apiVersion: v1
kind: Service
metadata:
  namespace: cybersec
  name: app2
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: app2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cybersec
  name: app2
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 1
  template:
    metadata:
      labels:
        app: app2
        name: app2
    spec:
      containers:
        - name: app2
          image: sautax/cybersec-app-2:1.1
          ports:
            - containerPort: 3000
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
