apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-networkpolicy-inter-service
  annotations:
    policies.kyverno.io/title: Add Network Policy
    policies.kyverno.io/category: Multi-Tenancy, EKS Best Practices
    policies.kyverno.io/subject: NetworkPolicy
    policies.kyverno.io/minversion: 1.6.0
spec:
  rules:
    - name: inter-service
      match:
        any:
          - resources:
              kinds:
                - Namespace
      generate:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        name: inter-service
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          spec:
            # select all pods in the namespace
            podSelector:
              matchLabels:
                app.kubernetes.io/name: "app1"
            # deny all traffic
            policyTypes:
              - Ingress
            ingress:
              - from:
                  - podSelector:
                    matchLabels:
                      app.kubernetes.io/name: "app2"
                ports:
                  - protocol: TCP
                    port: 3000
