apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-networkpolicy-http-ingress
  annotations:
    policies.kyverno.io/title: Add Network Policy
    policies.kyverno.io/category: Multi-Tenancy, EKS Best Practices
    policies.kyverno.io/subject: NetworkPolicy
    policies.kyverno.io/minversion: 1.6.0
spec:
  rules:
    - name: http-ingress
      match:
        any:
          - resources:
              kinds:
                - Namespace
      generate:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        name: http-ingress
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          spec:
            # select all pods in the namespace
            podSelector:
              matchLabels:
                name: "app1"
            # deny all traffic
            policyTypes:
              - Ingress
              - Egress
            egress:
              - to:
                  - namespaceSelector:
                      matchLabels:
                        app.kubernetes.io/name: kube-system
                ports:
                  - protocol: TCP
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        name: kube-system
                ports:
                  - protocol: TCP
                    port: 3000
